### ISSUE TITLE
eradicate and black

### ISSUE THREAD

**Issue by tobiasraabe** [myint/eradicate#11]
Repost of https://github.com/sobolevn/flake8-eradicate/issues/8.

Hi,

Thanks for the tool. Unfortunately, eradicate recognizes # fmt: on and # fmt: off as commented out code whereas the comments identify blocks which should not be formatted with black. Is it possible to exclude these patterns?

Best

**Comment by myint** [comment]
Looks like Python 3 considers `fmt: on` to be valid Python syntax. Python 2 does not though.

https://github.com/myint/eradicate/blob/a1f49510bb9c8894f875c0d26849f10c8bfd1a58/eradicate.py#L83-L87

We might need need to explicitly exclude syntax that follows the pattern `something_here: something_here` from being considered Python code.

**Comment by bskinn** [comment]
```
>>> fmt = "foo"
>>> on = "bar"
>>> {
... fmt: on
... }
{'foo': 'bar'}
```

**Comment by vaneseltine** [comment]
It's a slightly bigger problem than that, since `something_here: something_here` is [the syntax to annotate type starting in 3.6](https://www.python.org/dev/peps/pep-0526/#specification).

```
>>> on = int
>>> fmt: on
```

**Comment by uhbif19** [comment]
Probably issue with typing can be resolved using option for ignoring such cases. I thing `var: type` alone should be not very common.

**Comment by uhbif19** [comment]
@myint It seems like this is already covered by aggressive setting or not?

https://github.com/myint/eradicate/blob/master/eradicate.py#L66

**Comment by r4rdsn** [comment]
> I thing `var: type` alone should be not very common.

it's rather common in annotations of class attributes, especially in [dataclasses](https://docs.python.org/3/library/dataclasses.html)

**Comment by Dreamsorcerer** [comment]
Looks like the linked whitelist feature should be the way to go. It only requires these 2 statements to be whitelisted.

**Comment by sobolevn** [comment]
@myint hi! 

Several my projects do depend on `eradicate` (including https://github.com/sobolevn/flake8-eradicate and https://github.com/wemake-services/wemake-python-styleguide)

And I can see that you don't have much time to work on open-source. Maybe you can add me and other active contributors as maintainers? So we can help you with some on-going tasks like bugfixes and feature requests.

I would love to help! 👍
