### ISSUE TITLE
Type ignore comments is a false positive.

### ISSUE THREAD

**Issue by proofit404** [myint/eradicate#15]
Write `# type: ignore` at the beginning of the file will be considered by this plugin as dead code.

Initially reported to https://github.com/sobolevn/flake8-eradicate/issues/68

**Comment by proofit404** [comment]
@sobolevn Thanks for fixing it!

`# isort: skip` did the same as well unfortunately.

**Comment by sobolevn** [comment]
@proofit404 can you please add `isort` to the whitelist?
