### ISSUE TITLE
Various non-code comments removed

### ISSUE THREAD

**Issue by The-Compiler** [myint/eradicate#2]
I just tried out eradicate, and it removed those comments which aren't sourcecode:

* `# See # https://github.com/The-Compiler/qutebrowser/issues/263`
* `# Qt >= 5.4` (okay, this one is probably hard to detect)
* `# anything (yet)`
* `# configparser can't handle = in keys :(`

**Comment by myint** [comment]
I've fixed the last case.

I think supporting the second and third will weaken the heuristic too much. The first one seems a bit odd.

**Comment by The-Compiler** [comment]
Thanks!

Yeah, it was actually a typo - when moving the line after that upwards (with vim's `J`) I forgot to remove the `#`.
