### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by sils** [myint/eradicate#4]
Hi, I've tried eradicate on the coala project and it came up with only false positives. Here's a visualization of the results: http://pastebin.com/qbfg1Ecc (I assure you it's the latest eradicator release from pypi working behind the scenes, just think this is better to read and contains diffs with context so you can see whats going on.)

Especially if there's code between noncode lines I think it makes sense to exclude them, also there's a false negative in cindex.py which would be nice to have handled, I think something starting with a bracket may be easily declared as positive?

**Comment by myint** [comment]
I've fixed @underyx's example in the latest release. And I've resolved a few of @sils' examples in `master`.

**Comment by underyx** [comment]
Awesome, @myint, thanks!

We're using eradicate through coala, so I'll ask them to bump the eradicate version to 0.2 then.
