### ISSUE TITLE
Is it time to issue a new release?

### ISSUE THREAD

**Issue by proofit404** [myint/eradicate#42]
```python
# mypy: disable-error-code = misc
```

At the moment comment like this would be considered an error.

Usually, users forced to write such comments because of `typing.Any` was used inside third-party library imported by the users code. For example, it's a problem with popular FastAPI and Typer frameworks when you have strict mypy setting that even expression inside a function can't be evaluated to Any. So, it's kinda annoing.

That was already fixed in the upstream branch.

It would be nice to make it available on PyPI.

Thoughts?

Best regards,
Josiah.

**Comment by sobolevn** [comment]
`2.2.0` is released.
