### ISSUE TITLE
Misses methods declaration with annotated return types

### ISSUE THREAD

**Issue by sobolevn** [myint/eradicate#8]
Hi, thanks for this awesome plugin. I am using it in production, it works great.
However, I have found out that it misses this case:

```
-# class CommentedClass(object):
 #     def __init__(self, prop: int) -> None:
-#         self.property = prop
 
 #     def __str__(self) -> str:
-#         return self.__class__.__name__
 
-#    def set_prop(self, prop: int):
-#        self.prop = prop
 
-#    def get_prop(self):
-#        return self.prop
```

Look, all method declarations with annotated return types are ignored in this diff. The same goes for the regular functions, not just methods.
This may lead to some false negative behavior. 

P.S. I have made a `flake8` plugin to check my codebase with `eradicate`, check it out: https://github.com/sobolevn/flake8-eradicate

**Comment by myint** [comment]
Closed by #10.

**Comment by sobolevn** [comment]
@myint awesome! Thank you.

Do you plan to release it sometime soon?

**Comment by myint** [comment]
@sobolevn Just released:

https://pypi.org/project/eradicate/1.0/
